/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.phone.view.form.thuoctinh;

import com.core.entity.KetQua;
import com.core.model.request.ThuocTinhRequest;
import com.core.model.response.SanPhamResponse;
import com.core.model.response.ThuocTinhResponse;
import com.core.service.impl.ThuocTinhServiceImpl;
import com.phone.custom.component.Notification;
import com.phone.swing.Combobox;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class FormCTTTHang extends javax.swing.JFrame {

    public String tenBang;
    private Notification notiSuccess;
    private Notification notiWarring;
    private ThuocTinhServiceImpl impl = new ThuocTinhServiceImpl();
    private FormThuocTinh parentForm;
    private DefaultTableModel defaultTableModel = new DefaultTableModel();
    private List<ThuocTinhResponse> list = new ArrayList<>();
    private List<ThuocTinhResponse> list1 = new ArrayList<>();

    /**
     * Creates new form FormCTTT
     */
    public FormCTTTHang() {
        initComponents();
        setLocationRelativeTo(null);
        txtID.setText("");
    }

    public void handleEvent(String name, String tenBang1) {
        txtTitleCTTT.setText(name);
        txtTenCTTT.setText("Tên " + name);
        this.tenBang = tenBang1;
        fillTable();
        getCbo();
    }

    public void setComboBoxValue(int hoatDong) {
        if (hoatDong == 1) {
            jComboBox1.setSelectedItem("Đang hoạt động");
        } else {
            jComboBox1.setSelectedItem("Không hoạt động");
        }
    }

    public void fillForm(ThuocTinhResponse thuocTinhResponse) {
        txtID.setText(String.valueOf(thuocTinhResponse.getId()));
        txtHang.setText(String.valueOf(thuocTinhResponse.getName()));
        setComboBoxValue(thuocTinhResponse.getHoatDong());
    }

    public void getCbo() {
        jComboBox1.removeAllItems();
        jComboBox1.addItem("Đang hoạt động");
        jComboBox1.addItem("Không hoạt động");
    }

    public void fillTable() {
        defaultTableModel = (DefaultTableModel) tbList.getModel();
        defaultTableModel.setColumnIdentifiers(new Object[]{"ID", "Tên " + tenBang, "Hoạt Động"});
        list = impl.findAll(tenBang);
        defaultTableModel.setRowCount(0);
        for (ThuocTinhResponse thuocTinhResponse : list) {
            defaultTableModel.addRow(thuocTinhResponse.toRowTable());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTenCTTT = new javax.swing.JLabel();
        txtHang = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtID = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbList = new javax.swing.JTable();
        txtTitleCTTT = new javax.swing.JLabel();
        Hủy = new com.phone.swing.ButtonDanger();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 3, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/phone/resources/icons/social-media.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Hoạt động");

        txtTenCTTT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTenCTTT.setText("Hãng");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Id");

        txtID.setText("Id");

        jButton1.setText("Thêm ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sửa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Xóa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tbList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "STT", "Tên ", "Hoạt Động"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbList.setRowHeight(50);
        tbList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbList);
        if (tbList.getColumnModel().getColumnCount() > 0) {
            tbList.getColumnModel().getColumn(0).setMinWidth(50);
            tbList.getColumnModel().getColumn(0).setPreferredWidth(50);
            tbList.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        txtTitleCTTT.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        txtTitleCTTT.setText("Hãng");

        Hủy.setText("Hủy");
        Hủy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HủyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addComponent(txtTitleCTTT)
                        .addContainerGap(308, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(txtTenCTTT)
                                    .addComponent(jLabel3))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(136, 136, 136))
                                        .addComponent(txtHang)))
                                .addGap(109, 109, 109)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Hủy, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTitleCTTT)
                            .addComponent(jLabel1))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtID)
                            .addComponent(jLabel5))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenCTTT)
                            .addComponent(txtHang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Hủy, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (txtHang.getText().isEmpty()) {
            notiWarring = new Notification(this, Notification.Type.WARNING, Notification.Location.TOP_RIGHT, "Chưa nhập");
            notiWarring.showNotification();
            txtHang.requestFocus();
        } else {
            int hoatDong = jComboBox1.getSelectedItem().equals("Đang hoạt động") ? 1 : 0;
            KetQua ketQua = impl.create1(tenBang, txtHang.getText(), hoatDong);
            if (ketQua.getIdKetQua() == 1) {
                notiSuccess = new Notification(this, Notification.Type.SUCCESS, Notification.Location.TOP_RIGHT, "Thêm " + tenBang + " thành công");
                notiSuccess.showNotification();
                fillTable();
                txtHang.setText("");
                txtHang.requestFocus();
            } else {
                notiWarring = new Notification(this, Notification.Type.WARNING, Notification.Location.TOP_RIGHT, "That bai");
                notiWarring.showNotification();
            }
        }
//         readForm();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void HủyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HủyActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_HủyActionPerformed

    private void tbListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListMouseClicked
        // TODO add your handling code here:
        int index = tbList.getSelectedRow();
        fillForm(list.get(index));
    }//GEN-LAST:event_tbListMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (txtHang.getText().isEmpty()) {
        notiWarring = new Notification(this, Notification.Type.WARNING, Notification.Location.TOP_RIGHT, "Chưa nhập tên " + tenBang);
        notiWarring.showNotification();
        txtHang.requestFocus();
    } else {
        try {
            int id = Integer.parseInt(txtID.getText());
            int hoatDong = jComboBox1.getSelectedItem().equals("Đang hoạt động") ? 1 : 0;
            
            ThuocTinhResponse data = new ThuocTinhResponse();
            data.setName(txtHang.getText());
            
            Boolean ketQua = impl.update1(tenBang, id, data, hoatDong);
            
            if (ketQua) {
                notiSuccess = new Notification(this, Notification.Type.SUCCESS, Notification.Location.TOP_RIGHT, "Cập nhật " + tenBang + " thành công");
                notiSuccess.showNotification();
                fillTable();
                txtHang.setText("");
                txtID.setText("");
                txtHang.requestFocus();
            } else {
                notiWarring = new Notification(this, Notification.Type.WARNING, Notification.Location.TOP_RIGHT, "Cập nhật thất bại");
                notiWarring.showNotification();
            }
        } catch (NumberFormatException e) {
            notiWarring = new Notification(this, Notification.Type.WARNING, Notification.Location.TOP_RIGHT, "ID không hợp lệ");
            notiWarring.showNotification();
        } catch (Exception e) {
            e.printStackTrace();
            notiWarring = new Notification(this, Notification.Type.WARNING, Notification.Location.TOP_RIGHT, "Lỗi: " + e.getMessage());
            notiWarring.showNotification();
        }
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (txtID.getText().isEmpty()) {
            notiWarring = new Notification(this, Notification.Type.WARNING, Notification.Location.TOP_RIGHT, "Chưa chọn" + tenBang + " để xóa");
            notiWarring.showNotification();
            txtHang.requestFocus();
        } else {
            int option = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa " + tenBang + " này?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                boolean ketQua = impl.delete(tenBang, Integer.valueOf(txtID.getText()));
                if (ketQua) {
                    notiSuccess = new Notification(this, Notification.Type.SUCCESS, Notification.Location.TOP_RIGHT, "Xóa " + tenBang + " thành công");
                    notiSuccess.showNotification();
                    fillTable();
                    txtHang.setText("");
                    txtID.setText("");
                    txtHang.requestFocus();
                } else {
                    notiWarring = new Notification(this, Notification.Type.WARNING, Notification.Location.TOP_RIGHT, "Xóa thất bại");
                    notiWarring.showNotification();
                }
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCTTTHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCTTTHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCTTTHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCTTTHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCTTTHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.phone.swing.ButtonDanger Hủy;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbList;
    private javax.swing.JTextField txtHang;
    private javax.swing.JLabel txtID;
    private javax.swing.JLabel txtTenCTTT;
    private javax.swing.JLabel txtTitleCTTT;
    // End of variables declaration//GEN-END:variables

}
