/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.phone.view.form.voucher;

import com.core.model.response.VouCherResponse;
import com.core.repository.VoucherRepository;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class FormThemVoucher extends javax.swing.JFrame {

    VoucherRepository vouCherRepository = new VoucherRepository();
    List<VouCherResponse> list = new ArrayList<>();
    int index;

    /**
     * Creates new form FormThemVoucher
     */
    public FormThemVoucher() {
        initComponents();
        setLocationRelativeTo(null);
    }

    private VouCherResponse getVouCher() {
        VouCherResponse vc = new VouCherResponse();
        if (index >= 0 && index < list.size()) {
            vc.setId(list.get(index).getId());
            vc.setSTT(list.get(index).getSTT());
        }

        try {
            vc.setMaVouCher(txtMagiamGia.getText().trim());
            vc.setTenVouCher(txtTenPhieuGiamGia.getText().trim());
            vc.setGiaTriToiThieuApDung(Float.parseFloat(txtGiaTriToiThieuDuocApDung.getText().trim()));
            vc.setPhanTramGiam(Integer.parseInt(txtPhanTramGiam.getText().trim()));
            if (vc.getPhanTramGiam() >= 100) {
                JOptionPane.showMessageDialog(this, "Phần trăm giảm phải từ 0-100", "Lỗi", 0);
                return null;
            }
            vc.setSoTienDuocGiamToiDa(Float.parseFloat(txtSoTienToiDaDuocGiam.getText().trim()));
            vc.setNgayBatDau(txtNgayBatDau.getText().trim());
            vc.setNgayKetThuc(txtNgayKetThuc.getText().trim());
            LocalDate startDate = LocalDate.parse(vc.getNgayBatDau());
            LocalDate endDate = LocalDate.parse(vc.getNgayKetThuc());
            LocalDate today = LocalDate.now();
            if (startDate.isBefore(today)) {
                JOptionPane.showMessageDialog(this, "Ngày bắt đầu phải sau hôm nay", "Lỗi", 0);
                return null;
            }
            
            if (startDate.isBefore(endDate)) {
                
            } else if (startDate.isEqual(endDate)) {
                JOptionPane.showMessageDialog(this, "Ngày bắt đầu phải khác ngày kết thúc", "Lỗi", 0);
                return null;
            } else {
                JOptionPane.showMessageDialog(this, "Ngày bắt đầu phải trước ngày kết thúc", "Lỗi", 0);
                return null;
            }
            
            vc.setNguoiTao("admin");
            vc.setSoLuong(Integer.parseInt(txtSoLuong.getText().trim()));
            vc.setHoatDong(1);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập các giá trị số hợp lệ!");
            return null;
        }

        return vc;
    }

    private void Clear() {
        txtGiaTriToiThieuDuocApDung.setText("");
        txtMagiamGia.setText("");
        txtNgayBatDau.setText("");
        txtNgayKetThuc.setText("");
        txtPhanTramGiam.setText("");
        txtSoLuong.setText("");
        txtSoTienToiDaDuocGiam.setText("");
        txtTenPhieuGiamGia.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtMagiamGia = new com.phone.swing.TextField();
        txtTenPhieuGiamGia = new com.phone.swing.TextField();
        txtPhanTramGiam = new com.phone.swing.TextField();
        txtGiaTriToiThieuDuocApDung = new com.phone.swing.TextField();
        txtNgayBatDau = new com.phone.swing.TextField();
        txtSoTienToiDaDuocGiam = new com.phone.swing.TextField();
        txtNgayKetThuc = new com.phone.swing.TextField();
        txtSoLuong = new com.phone.swing.TextField();
        btnClear = new com.phone.swing.ButtonPrimary();
        btnAdd = new com.phone.swing.ButtonPrimary();
        btnClear1 = new com.phone.swing.ButtonPrimary();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Thêm VouCher Mới");

        txtMagiamGia.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtMagiamGia.setLabelText("Mã Phiếu Giảm Giá");

        txtTenPhieuGiamGia.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtTenPhieuGiamGia.setLabelText("Tên Phiếu Giảm Giá");

        txtPhanTramGiam.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtPhanTramGiam.setLabelText("Phần Trăm Giảm");

        txtGiaTriToiThieuDuocApDung.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtGiaTriToiThieuDuocApDung.setLabelText("Giá Trị Tối Thiểu Được Áp Dụng");

        txtNgayBatDau.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtNgayBatDau.setLabelText("Ngày Bắt Đầu (yyyy-mm-dd)");

        txtSoTienToiDaDuocGiam.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtSoTienToiDaDuocGiam.setLabelText("Số Tiền Được Giảm Tối Đa");

        txtNgayKetThuc.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtNgayKetThuc.setLabelText("Ngày Kết Thúc (yyyy-mm-dd)");

        txtSoLuong.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtSoLuong.setLabelText("Số Lượng");

        btnClear.setText("Clear");
        btnClear.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnAdd.setText("ADD");
        btnAdd.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnClear1.setText("Back");
        btnClear1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtMagiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(txtTenPhieuGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtGiaTriToiThieuDuocApDung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSoTienToiDaDuocGiam, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNgayBatDau, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPhanTramGiam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgayKetThuc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnClear1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMagiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenPhieuGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGiaTriToiThieuDuocApDung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhanTramGiam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoTienToiDaDuocGiam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        this.Clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        VouCherResponse vc = getVouCher();

        if (vc == null) {

            return;
        }

        // Kiểm tra thông tin nhập vào
        if (vc.getMaVouCher().isEmpty()
                || vc.getTenVouCher().isEmpty()
                || vc.getGiaTriToiThieuApDung() <= 0
                || vc.getPhanTramGiam() <= 0
                || vc.getSoTienDuocGiamToiDa() <= 0
                || vc.getNgayBatDau().isEmpty()
                || vc.getNgayKetThuc().isEmpty()
                || vc.getSoLuong() <= 0) {

            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin hợp lệ!");
            return;
        }

        // Thực hiện thêm voucher vào cơ sở dữ liệu
        boolean success = vouCherRepository.getADD(vc);

        if (success) {
            javax.swing.JOptionPane.showMessageDialog(this, "Thêm voucher thành công!");
            list.add(vc);
            Clear();

            FormVoucher formVouchertest = new FormVoucher();
            formVouchertest.showFromAll();
            
            formVouchertest.setVisible(true);

            // Đóng form hiện tại
            dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Thêm voucher thất bại!");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear1ActionPerformed
        FormVoucher formVoucher = new FormVoucher();
        formVoucher.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnClear1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormThemVoucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormThemVoucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormThemVoucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormThemVoucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormThemVoucher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.phone.swing.ButtonPrimary btnAdd;
    private com.phone.swing.ButtonPrimary btnClear;
    private com.phone.swing.ButtonPrimary btnClear1;
    private javax.swing.JLabel jLabel1;
    private com.phone.swing.TextField txtGiaTriToiThieuDuocApDung;
    private com.phone.swing.TextField txtMagiamGia;
    private com.phone.swing.TextField txtNgayBatDau;
    private com.phone.swing.TextField txtNgayKetThuc;
    private com.phone.swing.TextField txtPhanTramGiam;
    private com.phone.swing.TextField txtSoLuong;
    private com.phone.swing.TextField txtSoTienToiDaDuocGiam;
    private com.phone.swing.TextField txtTenPhieuGiamGia;
    // End of variables declaration//GEN-END:variables
}
